spring.application.name=knowledge-gap-backend
<<<<<<< HEAD
=======
spring.datasource.url=jdbc:postgresql://localhost:5432/knowledge_gap_db
spring.datasource.username=postgres
spring.datasource.password=Bhargav@2005
>>>>>>> 30c46618f56b09478436e031f43a65a81062d62e

spring.datasource.url=jdbc:postgresql://db.bdnjaslgxaljiryxpnxp.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Supabase@29
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true