spring.application.name=knowledge-gap-backend

spring.datasource.url=jdbc:postgresql://db.bdnjaslgxaljiryxpnxp.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=Supabase@29
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true