/* ──────────────────────────────────────────────
   data.js  –  Mock data for HR Dashboard
   Frontend only – no API
   ────────────────────────────────────────────── */

/* ── EMPLOYEES ─────────────────────────────── */
export const employees = [
    {
        id: "EMP-00101",
        name: "Jane Doe",
        email: "jane.doe@acmecorp.com",
        phone: "+1 (555) 012-3456",
        avatar: "JD",
        role: "HR Manager",
        department: "Human Resources",
        location: "New York, NY",
        manager: "Robert Chen",
        joinDate: "2019-03-14",
        status: "active",
        contractType: "Full-time",
    },
    {
        id: "EMP-00102",
        name: "Michael Torres",
        email: "m.torres@acmecorp.com",
        phone: "+1 (555) 234-5678",
        avatar: "MT",
        role: "Senior Engineer",
        department: "Engineering",
        location: "Austin, TX",
        manager: "Linda Park",
        joinDate: "2018-07-02",
        status: "active",
        contractType: "Full-time",
    },
    {
        id: "EMP-00103",
        name: "Priya Sharma",
        email: "p.sharma@acmecorp.com",
        phone: "+1 (555) 345-6789",
        avatar: "PS",
        role: "Data Analyst",
        department: "Analytics",
        location: "San Francisco, CA",
        manager: "James Liu",
        joinDate: "2020-11-18",
        status: "active",
        contractType: "Full-time",
    },
    {
        id: "EMP-00104",
        name: "David Reynolds",
        email: "d.reynolds@acmecorp.com",
        phone: "+1 (555) 456-7890",
        avatar: "DR",
        role: "UX Designer",
        department: "Design",
        location: "Chicago, IL",
        manager: "Sarah Kim",
        joinDate: "2021-04-05",
        status: "active",
        contractType: "Full-time",
    },
    {
        id: "EMP-00105",
        name: "Sarah Kim",
        email: "s.kim@acmecorp.com",
        phone: "+1 (555) 567-8901",
        avatar: "SK",
        role: "Design Lead",
        department: "Design",
        location: "Chicago, IL",
        manager: "Robert Chen",
        joinDate: "2017-09-22",
        status: "active",
        contractType: "Full-time",
    },
    {
        id: "EMP-00106",
        name: "James Liu",
        email: "j.liu@acmecorp.com",
        phone: "+1 (555) 678-9012",
        avatar: "JL",
        role: "Analytics Manager",
        department: "Analytics",
        location: "San Francisco, CA",
        manager: "Robert Chen",
        joinDate: "2016-02-10",
        status: "active",
        contractType: "Full-time",
    },
    {
        id: "EMP-00107",
        name: "Emily Watson",
        email: "e.watson@acmecorp.com",
        phone: "+1 (555) 789-0123",
        avatar: "EW",
        role: "Recruiter",
        department: "Human Resources",
        location: "New York, NY",
        manager: "Jane Doe",
        joinDate: "2022-01-17",
        status: "active",
        contractType: "Full-time",
    },
    {
        id: "EMP-00108",
        name: "Carlos Mendes",
        email: "c.mendes@acmecorp.com",
        phone: "+1 (555) 890-1234",
        avatar: "CM",
        role: "Backend Engineer",
        department: "Engineering",
        location: "Austin, TX",
        manager: "Michael Torres",
        joinDate: "2021-08-30",
        status: "on-leave",
        contractType: "Full-time",
    },
    {
        id: "EMP-00109",
        name: "Linda Park",
        email: "l.park@acmecorp.com",
        phone: "+1 (555) 901-2345",
        avatar: "LP",
        role: "Engineering Director",
        department: "Engineering",
        location: "Seattle, WA",
        manager: "Robert Chen",
        joinDate: "2015-06-01",
        status: "active",
        contractType: "Full-time",
    },
    {
        id: "EMP-00110",
        name: "Aisha Patel",
        email: "a.patel@acmecorp.com",
        phone: "+1 (555) 012-3457",
        avatar: "AP",
        role: "Compliance Officer",
        department: "Legal & Compliance",
        location: "New York, NY",
        manager: "Robert Chen",
        joinDate: "2019-10-14",
        status: "active",
        contractType: "Full-time",
    },
];

/* ── SKILLS ─────────────────────────────────── */
export const skills = [
    { id: "SKL-001", name: "Data Literacy", category: "Analytics", proficiency: "Advanced", level: 85 },
    { id: "SKL-002", name: "React.js", category: "Frontend", proficiency: "Expert", level: 95 },
    { id: "SKL-003", name: "UI/UX Design", category: "Design", proficiency: "Intermediate", level: 60 },
    { id: "SKL-004", name: "Python", category: "Backend", proficiency: "Advanced", level: 80 },
    { id: "SKL-005", name: "Agile / Scrum", category: "Management", proficiency: "Intermediate", level: 65 },
    { id: "SKL-006", name: "Cybersecurity", category: "Security", proficiency: "Beginner", level: 30 },
    { id: "SKL-007", name: "Machine Learning", category: "Analytics", proficiency: "Intermediate", level: 55 },
    { id: "SKL-008", name: "Node.js", category: "Backend", proficiency: "Advanced", level: 78 },
    { id: "SKL-009", name: "Communication", category: "Soft Skills", proficiency: "Expert", level: 92 },
    { id: "SKL-010", name: "SQL", category: "Backend", proficiency: "Advanced", level: 83 },
    { id: "SKL-011", name: "Figma", category: "Design", proficiency: "Intermediate", level: 58 },
    { id: "SKL-012", name: "Conflict Resolution", category: "Soft Skills", proficiency: "Advanced", level: 76 },
    { id: "SKL-013", name: "TypeScript", category: "Frontend", proficiency: "Advanced", level: 82 },
    { id: "SKL-014", name: "AI & Automation", category: "Analytics", proficiency: "Beginner", level: 25 },
    { id: "SKL-015", name: "Leadership", category: "Management", proficiency: "Advanced", level: 88 },
    { id: "SKL-016", name: "Tailwind CSS", category: "Frontend", proficiency: "Expert", level: 96 },
    { id: "SKL-017", name: "Docker", category: "DevOps", proficiency: "Intermediate", level: 62 },
    { id: "SKL-018", name: "Kubernetes", category: "DevOps", proficiency: "Beginner", level: 28 },
    { id: "SKL-019", name: "Public Speaking", category: "Soft Skills", proficiency: "Advanced", level: 79 },
    { id: "SKL-020", name: "Project Management", category: "Management", proficiency: "Expert", level: 91 },
];

/* ── COMPETENCIES ───────────────────────────── */
export const competencies = [
    { id: "CMP-001", skill: "Data Literacy", category: "Analytics", required: "Advanced", current: "Intermediate" },
    { id: "CMP-002", skill: "React.js", category: "Frontend", required: "Expert", current: "Expert" },
    { id: "CMP-003", skill: "UI/UX Design", category: "Design", required: "Advanced", current: "Beginner" },
    { id: "CMP-004", skill: "Python", category: "Backend", required: "Advanced", current: "Advanced" },
    { id: "CMP-005", skill: "Agile / Scrum", category: "Management", required: "Advanced", current: "Intermediate" },
    { id: "CMP-006", skill: "Cybersecurity", category: "Security", required: "Intermediate", current: "Beginner" },
    { id: "CMP-007", skill: "Machine Learning", category: "Analytics", required: "Advanced", current: "Intermediate" },
    { id: "CMP-008", skill: "Communication", category: "Soft Skills", required: "Expert", current: "Expert" },
    { id: "CMP-009", skill: "SQL", category: "Backend", required: "Advanced", current: "Advanced" },
    { id: "CMP-010", skill: "Leadership", category: "Management", required: "Expert", current: "Advanced" },
    { id: "CMP-011", skill: "Conflict Resolution", category: "Soft Skills", required: "Advanced", current: "Advanced" },
    { id: "CMP-012", skill: "TypeScript", category: "Frontend", required: "Expert", current: "Advanced" },
    { id: "CMP-013", skill: "AI & Automation", category: "Analytics", required: "Intermediate", current: "Beginner" },
    { id: "CMP-014", skill: "Figma", category: "Design", required: "Intermediate", current: "Intermediate" },
    { id: "CMP-015", skill: "Tailwind CSS", category: "Frontend", required: "Advanced", current: "Expert" },
    { id: "CMP-016", skill: "Node.js", category: "Backend", required: "Advanced", current: "Advanced" },
    { id: "CMP-017", skill: "Docker", category: "DevOps", required: "Advanced", current: "Intermediate" },
    { id: "CMP-018", skill: "Project Management", category: "Management", required: "Expert", current: "Expert" },
];

/* ── DASHBOARD STATISTICS ────────────────────── */
export const dashboardStats = {
    summary: {
        totalEmployees: { value: 240, trend: "+5%", trendUp: true, trendLabel: "from last month" },
        activeTrainings: { value: 12, trend: "+3", trendUp: true, trendLabel: "new this week" },
        openMentorships: { value: 45, trend: "-2", trendUp: false, trendLabel: "from last month" },
        avgAssessmentScore: { value: "85%", trend: "+2%", trendUp: true, trendLabel: "from last quarter" },
    },

    knowledgeGaps: [
        { skill: "Data Literacy", gap: 68 },
        { skill: "AI & Automation", gap: 82 },
        { skill: "Cybersecurity", gap: 55 },
        { skill: "Agile / Scrum", gap: 43 },
        { skill: "Communication", gap: 30 },
        { skill: "Docker", gap: 60 },
        { skill: "Machine Learning", gap: 72 },
    ],

    trainingProgress: [
        { label: "Compliance & Ethics", percent: 78, completed: 187, total: 240 },
        { label: "Leadership Development", percent: 52, completed: 44, total: 85 },
        { label: "Technical Upskilling", percent: 91, completed: 109, total: 120 },
        { label: "DEI Awareness", percent: 64, completed: 154, total: 240 },
        { label: "Cybersecurity Awareness", percent: 38, completed: 46, total: 120 },
    ],

    recentActivity: [
        { id: 1, actor: "Sarah K.", action: "completed Compliance Training", time: "5 min ago", badge: "success" },
        { id: 2, actor: "Michael T.", action: "submitted a leave request", time: "22 min ago", badge: "warning" },
        { id: 3, actor: "New pairing", action: "created between Priya S. & James L.", time: "1 hr ago", badge: "info" },
        { id: 4, actor: "Q3 Assessment", action: "results published for Engineering", time: "2 hrs ago", badge: "primary" },
        { id: 5, actor: "David R.", action: "enrolled in Leadership Path", time: "3 hrs ago", badge: "success" },
        { id: 6, actor: "System", action: "payroll report generated for August", time: "5 hrs ago", badge: "secondary" },
        { id: 7, actor: "Aisha P.", action: "completed Cybersecurity Awareness module", time: "6 hrs ago", badge: "success" },
        { id: 8, actor: "Emily W.", action: "posted a new knowledge article", time: "8 hrs ago", badge: "info" },
    ],

    departmentBreakdown: [
        { department: "Engineering", headcount: 72, activeTrainings: 4, avgScore: 87 },
        { department: "Human Resources", headcount: 18, activeTrainings: 2, avgScore: 91 },
        { department: "Analytics", headcount: 34, activeTrainings: 3, avgScore: 84 },
        { department: "Design", headcount: 22, activeTrainings: 1, avgScore: 82 },
        { department: "Legal & Compliance", headcount: 15, activeTrainings: 1, avgScore: 89 },
        { department: "Product", headcount: 29, activeTrainings: 2, avgScore: 85 },
        { department: "Sales", headcount: 50, activeTrainings: 3, avgScore: 78 },
    ],
};

/* ── MENTORSHIPS ─────────────────────────────── */
export const mentorships = [
    { id: "MNT-001", mentor: "Jane Doe", mentee: "Emily Watson", focus: "HR Strategy", status: "active", startDate: "2026-05-01" },
    { id: "MNT-002", mentor: "Linda Park", mentee: "Carlos Mendes", focus: "Backend Architecture", status: "paused", startDate: "2026-03-15" },
    { id: "MNT-003", mentor: "James Liu", mentee: "Priya Sharma", focus: "Data Analytics", status: "active", startDate: "2026-06-10" },
    { id: "MNT-004", mentor: "Sarah Kim", mentee: "David Reynolds", focus: "UX Leadership", status: "active", startDate: "2026-04-20" },
    { id: "MNT-005", mentor: "Michael Torres", mentee: "Aisha Patel", focus: "Tech & Compliance", status: "completed", startDate: "2025-11-01" },
];

/* ── ASSESSMENTS ─────────────────────────────── */
export const assessments = [
    { id: "ASS-001", title: "Q3 2026 Performance Review", department: "Engineering", status: "published", avgScore: 87, participants: 72, date: "2026-07-31" },
    { id: "ASS-002", title: "Q3 2026 Performance Review", department: "Design", status: "published", avgScore: 82, participants: 22, date: "2026-07-31" },
    { id: "ASS-003", title: "React Proficiency Assessment", department: "Frontend", status: "in-progress", avgScore: null, participants: 18, date: "2026-08-10" },
    { id: "ASS-004", title: "Data Literacy Quiz", department: "Analytics", status: "scheduled", avgScore: null, participants: 34, date: "2026-08-20" },
    { id: "ASS-005", title: "Compliance & Ethics Test", department: "All", status: "published", avgScore: 91, participants: 240, date: "2026-06-15" },
];

/* ── NOTIFICATIONS ───────────────────────────── */
export const notifications = [
    { id: "NTF-001", title: "New Leave Request", description: "John Doe submitted a leave request for Aug 10 – 14.", time: "2026-08-06T15:35:00", isUnread: true },
    { id: "NTF-002", title: "Performance Review Due", description: "Q3 reviews for your team are due by Aug 15.", time: "2026-08-06T14:48:00", isUnread: true },
    { id: "NTF-003", title: "Training Completed", description: "Sarah Kim completed the Compliance Training module.", time: "2026-08-06T12:20:00", isUnread: false },
    { id: "NTF-004", title: "New Mentorship Pairing", description: "Priya Sharma has been paired with James Liu.", time: "2026-08-06T10:05:00", isUnread: false },
    { id: "NTF-005", title: "Assessment Published", description: "Q3 Engineering Performance Review results are available.", time: "2026-08-05T17:00:00", isUnread: false },
];
